//Bloody Tale

(function () {
  const css = `
  #dictNav{
    width: 60vw;
    margin: 0 auto; 
    max-width: none; 
    display: flex;
    flex-direction: column;
    height: 90vh; 
    
    border-top: 1px solid;
    border-bottom: 1px solid;
    background: var (--bg-color);
    color: var (--text-color);
    overflow:hidden;
    font-family:Inter,system-ui,Arial,sans-serif;
  }
  #dictNav .hdr{
    display:flex;
    align-items:center;
    gap:.5rem;
    padding:.6rem .8rem;
    background: var (--bg-color);
    color: var (--text-color); 
    border-bottom: 1px solid;
    flex-shrink: 0; 
  }
  #dictNav .hdr .title{flex:1;font-weight:600}
  
  #dictNav .body{
    flex-grow: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
  }
  
  #dictNav .left{
    padding:.5rem;
    flex-grow: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
  }
  
  #dictNav input, #dictNav select{
    width:100%;
    box-sizing:border-box;
    padding:.45rem;
    border-radius:6px;
    border:1px solid;
    flex-shrink: 0;
  }
  
  #dictNav ul{
    list-style:none;
    padding:0;
    margin: 0;
    flex-grow: 1;
    overflow-y: auto;
    min-height: 0;
  }
  
  #dictNav li{
    padding:.2rem .5rem; 
    font-size: .9rem;
    line-height: 1.3;
    
    cursor: default; 
    border-bottom: 1px solid;
  }
  
  #dictNav .meta{
    font-size:.8rem;
    color:#666;
    margin-top: 0;
  }
  `;
  const s = document.createElement('style');
  s.textContent = css;
  document.head.appendChild(s);
})();

window.initDictNav = function (data) {
  if (!Array.isArray(data)) return;

  const placeholder = document.getElementById('Bloody-Tale');
  if (!placeholder) {
    console.error('Dictionary placeholder #Bloody-Tale not found.');
    return;
  }

  if (document.getElementById('dictNav')) return;
  const cont = document.createElement('div');
  cont.id = 'dictNav';

  cont.innerHTML = `
    <div class="hdr">
      <h2 class="title">「Conte Sanguinaire」</h2>
    </div>
    <div class="body">
      <div class="left">
        <input id="dictSearch" placeholder="Chercher..." />
        <select id="dictFilter" style="margin-top:.5rem"></select>
        <ul id="dictList"></ul>
      </div>
    </div>
  `;
  placeholder.appendChild(cont);

  const search = cont.querySelector('#dictSearch');
  const filter = cont.querySelector('#dictFilter');
  const list = cont.querySelector('#dictList');

  const entries = data.map((item, idx) => {
    return {
      id: idx,
      term: item.war || item.title || item.name || `Entry ${idx + 1}`,
      category: item.location || item.category || '—',
      meta: item.date || item.info || '',
    };
  });

  const cats = Array.from(new Set(entries.map((e) => e.category))).sort();
  filter.innerHTML =
    `<option value="">Toutes Localisations</option>` +
    cats.map((c) => `<option value="${c}">${c}</option>`).join('');

  function renderList() {
    const q = search.value.trim().toLowerCase();
    const cat = filter.value;
    list.innerHTML = '';
    const filtered = entries.filter((e) => {
      return (
        (!cat || e.category === cat) &&
        (!q || e.term.toLowerCase().includes(q) || e.meta.toLowerCase().includes(q))
      );
    });
    if (!filtered.length) {
      list.innerHTML = '<li style="color:#666">Pas de résultats</li>';
      return;
    }

    for (const e of filtered) {
      const li = document.createElement('li');
      li.innerHTML = `<strong>${escapeHtml(e.term)}</strong><div class="meta">${escapeHtml(e.category)} · ${escapeHtml(e.meta)}</div>`;
      list.appendChild(li);
    }
  }

  function escapeHtml(s) {
    return s.replace?.(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') || s;
  }

  search.addEventListener('input', renderList);
  filter.addEventListener('change', renderList);
  renderList();
};

Object.defineProperty(window, 'warsData', {
  configurable: true,
  set: function (v) {
    Object.defineProperty(window, 'warsData', { configurable: true, writable: true, value: v });
    try {
      if (window.initDictNav) window.initDictNav(v);
    } catch (e) {
      console.error(e);
    }
  },
  get: function () {
    return undefined;
  },
});

window.warsData = [
  {
    war: 'Conflits entre Lagash et Umma',
    location: 'Mésopotamie',
    date: 'XXVIe – XXIVe siècle av. J.-C.',
  },
  { war: 'Guerre entre Uruk et Kish', location: 'Mésopotamie', date: 'vers 2650 av. J.-C.' },
  {
    war: "Guerre entre Sargon d'Akkad et Lugal-zagesi",
    location: 'Mésopotamie',
    date: 'vers 2334 av. J.-C.',
  },
  {
    war: 'Guerres entre Isin et Larsa',
    location: 'Mésopotamie',
    date: 'XXe siècle av. J.-C.-1794 av. J.-C. environ',
  },
  {
    war: 'Guerres entre Babylone et Larsa',
    location: 'Mésopotamie',
    date: '1845 - 1763 av. J.-C. environ',
  },
  {
    war: 'Révolte des Benjaminites',
    location: 'Mésopotamie',
    date: '1773 - 1769 av. J.-C. environ',
  },
  { war: 'Guerre élamite de 1765 av. J.-C.', location: 'Mésopotamie', date: '1765-1763 av. J.-C.' },
  {
    war: "Guerre entre Babylone et l'Assyrie de 1235 av. J.-C.",
    location: 'Mésopotamie',
    date: 'vers 1235 av. J.-C.',
  },
  {
    war: "Guerre de l'unification entre la Haute-Egypte et la Basse-Egypte",
    location: 'Proche-Orient ancien',
    date: 'vers 3150 av. J.-C.',
  },
  { war: 'Bataille de Megiddo', location: 'Proche-Orient ancien', date: 'vers 1483 av.J-C' },
  {
    war: 'Première Bataille de Qadech',
    location: 'Proche-Orient ancien',
    date: 'autour de 1296 av.J-C',
  },
  {
    war: 'Deuxième Bataille de Qadesh',
    location: 'Proche-Orient ancien',
    date: 'autour de 1274 av. J.-C.',
  },
  { war: 'Bataille de Nihirya', location: 'Proche-Orient ancien', date: 'vers 1265 av.J-C' },
  { war: 'Bataille du delta du Nil', location: 'Proche-Orient ancien', date: 'vers 1190 av.J-C' },
  {
    war: 'Guerre de Troie',
    location: 'Anatolie/Grèce antique',
    date: 'XIIIe ou XIIe siècle av. J.-C.',
  },
  { war: 'Guerre lélantine', location: 'Grèce', date: '740 av. J.-C.' },
  { war: 'Première guerre de Messénie', location: 'Grèce', date: '737-716 av. J.-C.' },
  { war: 'Deuxième guerre de Messénie', location: 'Grèce', date: '668-654 av. J.-C.' },
  { war: 'Première guerre sacrée', location: 'Grèce', date: '600-590 av. J.-C.' },
  {
    war: "Conflit entre Étrusques, Carthaginois et Phocéens et bataille d'Alalia",
    location: 'Méditerranée',
    date: 'vers 540-535 av. J.-C.',
  },
  {
    war: "Guerre entre l'Assyrie et l'Urartu de 743 av. J.-C.",
    location: 'Mésopotamie',
    date: '743-735 av. J.-C.',
  },
  {
    war: "Guerre entre l'Assyrie et l'Urartu de 714 av. J.-C. ou huitième campagne de Sargon II",
    location: 'Mésopotamie',
    date: '714 av. J.-C.',
  },
  {
    war: 'Révolte babylonienne de 652 av. J.-C.',
    location: 'Mésopotamie',
    date: '652-648 av. J.-C.',
  },
  {
    war: "Guerre de Babylone et des Mèdes contre l'Assyrie",
    location: 'Mésopotamie',
    date: 'vers 625/620-609 av. J.-C.',
  },
  {
    war: 'Révolte de la Palestine de 589 av. J.-C.',
    location: 'Mésopotamie',
    date: '589-573 av. J.-C.',
  },
  { war: 'Guerres romano-sabelliennes', location: 'Rome antique', date: '509 - 390 av. J.-C.' },
  {
    war: 'Guerre des Mercenaires ou guerre inexpiable (Carthage)',
    location: 'Afrique',
    date: '241 - 238 av. J.-C.',
  },
  {
    war: "Campagnes d'Alexandre le Grand",
    location: 'Asie (Moyen-Orient)',
    date: '334 - 325 av. J.-C.',
  },
  { war: 'Guerres des diadoques', location: 'Asie (Moyen-Orient)', date: '323 - 281 av. J.-C.' },
  { war: 'Guerres de Syrie', location: 'Asie (Moyen-Orient)', date: '274 - 168 av. J.-C.' },
  { war: 'Première guerre de Syrie', location: 'Asie (Moyen-Orient)', date: '274 - 271 av. J.-C.' },
  { war: 'Deuxième guerre de Syrie', location: 'Asie (Moyen-Orient)', date: '260 - 253 av. J.-C.' },
  {
    war: 'Troisième guerre de Syrie',
    location: 'Asie (Moyen-Orient)',
    date: '246 - 241 av. J.-C.',
  },
  {
    war: 'Quatrième guerre de Syrie',
    location: 'Asie (Moyen-Orient)',
    date: '219 - 217 av. J.-C.',
  },
  {
    war: 'Cinquième guerre de Syrie',
    location: 'Asie (Moyen-Orient)',
    date: '202 - 195 av. J.-C.',
  },
  { war: 'Sixième guerre de Syrie', location: 'Asie (Moyen-Orient)', date: '170 - 168 av. J.-C.' },
  { war: 'Les Royaumes combattants', location: 'Asie (Moyen-Orient)', date: '476 - 221 av. J.-C.' },
  { war: "Révolte de l'Ionie", location: 'Grèce', date: '499 av. J.-C.-493 av. J.-C.' },
  { war: 'Première guerre médique', location: 'Grèce', date: '490 av. J.-C.' },
  {
    war: 'Première guerre gréco-punique ou Première guerre de Sicile',
    location: 'Grèce',
    date: '480 av. J.-C.',
  },
  { war: 'Deuxième guerre médique', location: 'Grèce', date: '480-479 av. J.-C.' },
  { war: 'Deuxième guerre sacrée', location: 'Grèce', date: '448 av. J.-C.' },
  { war: 'Guerre du Péloponnèse', location: 'Grèce', date: '431-404 av. J.-C.' },
  {
    war: 'Deuxième guerre gréco-punique ou deuxième guerre de Sicile',
    location: 'Grèce',
    date: '410 av. J.-C. -340 av. J.-C.',
  },
  { war: 'Guerre de Corinthe', location: 'Grèce', date: '395-387 av. J.-C.' },
  { war: 'Guerre des alliés', location: 'Grèce', date: '357-355 av. J.-C.' },
  { war: 'Troisième guerre sacrée', location: 'Grèce', date: '356-346 av. J.-C.' },
  { war: 'Guerre lamiaque', location: 'Grèce', date: '323-322 av. J.-C.' },
  {
    war: 'Troisième guerre gréco-punique ou Troisième guerre de Sicile',
    location: 'Grèce',
    date: '315 av. J.-C-307 av. J.-C.',
  },
  { war: 'Guerre chrémonidéenne', location: 'Grèce', date: '268-261 av. J.-C.' },
  { war: 'Guerre démétriaque', location: 'Grèce', date: '239-229 av. J.-C.' },
  { war: 'Guerre de Cléomène', location: 'Grèce', date: '229-222 av. J.-C.' },
  { war: 'Première guerre crétoise', location: 'Grèce', date: '205-200 av. J.-C.' },
  { war: 'Guerre contre Nabis', location: 'Grèce', date: '195 av. J.-C.' },
  { war: 'Seconde guerre crétoise', location: 'Grèce', date: '155-153 av. J.-C.' },
  { war: 'Guerres romano-sabelliennes', location: 'Rome antique', date: '509 - 390 av. J.-C.' },
  { war: 'Guerres entre Rome et Véies', location: 'Rome antique', date: '485 - 396 av. J.-C.' },
  {
    war: 'Première guerre entre Rome et Véies',
    location: 'Rome antique',
    date: '485 - 474 av. J.-C.',
  },
  {
    war: 'Deuxième guerre entre Rome et Véies',
    location: 'Rome antique',
    date: '438 - 425 av. J.-C.',
  },
  {
    war: 'Troisième guerre entre Rome et Véies',
    location: 'Rome antique',
    date: '406 - 396 av. J.-C.',
  },
  { war: 'Raids gaulois en Italie', location: 'Rome antique', date: '390 - 225 av. J.-C.' },
  { war: 'Guerre romano-èque', location: 'Rome antique', date: '389 - 388 av. J.-C.' },
  { war: 'Guerres romano-volsques', location: 'Rome antique', date: '389 - 341 av. J.-C.' },
  {
    war: 'Premières guerres romano-volsques',
    location: 'Rome antique',
    date: '389 - 367 av. J.-C.',
  },
  {
    war: 'Deuxièmes guerres romano-volsques',
    location: 'Rome antique',
    date: '358 - 341 av. J.-C.',
  },
  {
    war: 'Guerres entre Rome et la Ligue latine',
    location: 'Rome antique',
    date: '389 - 338 av. J.-C.',
  },
  { war: 'Guerres romano-latines', location: 'Rome antique', date: '389 - 354 av. J.-C.' },
  { war: 'Guerre latine', location: 'Rome antique', date: '340 - 338 av. J.-C.' },
  { war: 'Guerres romano-étrusques', location: 'Rome antique', date: '389 - 264 av. J.-C.' },
  { war: 'Première guerre romano-étrusque', location: 'Rome antique', date: '389 - 386 av. J.-C.' },
  { war: 'Deuxième guerre romano-étrusque', location: 'Rome antique', date: '358 - 351 av. J.-C.' },
  {
    war: 'Troisième guerre romano-étrusque',
    location: 'Rome antique',
    date: '311 - 308 av. J.-C.',
  },
  { war: "Conquête romaine de l'Étrurie", location: 'Rome antique', date: '302 - 264 av. J.-C.' },
  { war: 'Guerre romano-hernique', location: 'Rome antique', date: '362 - 358 av. J.-C.' },
  { war: 'Guerres romano-aurunces', location: 'Rome antique', date: '345 - 334 av. J.-C.' },
  { war: 'Première guerre romano-aurunce', location: 'Rome antique', date: '345 - 344 av. J.-C.' },
  { war: 'Deuxième guerre romano-aurunce', location: 'Rome antique', date: '335 - 334 av. J.-C.' },
  { war: 'Guerres samnites', location: 'Rome antique', date: '343 - 290 av. J.-C.' },
  { war: 'Première guerre samnite', location: 'Rome antique', date: '343 - 341 av. J.-C.' },
  { war: 'Deuxième guerre samnite', location: 'Rome antique', date: '327 - 304 av. J.-C.' },
  { war: 'Troisième guerre samnite', location: 'Rome antique', date: '298 - 290 av. J.-C.' },
  { war: 'Guerre entre Rome et Tarente', location: 'Rome antique', date: '282 - 272 av. J.-C.' },
  { war: 'Guerre de Pyrrhus en Italie', location: 'Rome antique', date: '280 - 275 av. J.-C.' },
  { war: 'Guerres puniques', location: 'Rome antique', date: '264 - 146 av. J.-C.' },
  { war: 'Première guerre punique', location: 'Rome antique', date: '264 - 241 av. J.-C.' },
  { war: 'Deuxième guerre punique', location: 'Rome antique', date: '218 - 201 av. J.-C.' },
  { war: 'Troisième guerre punique', location: 'Rome antique', date: '149 - 146 av. J.-C.' },
  { war: "Guerres d'Illyrie", location: 'Rome antique', date: '229 - 219 av. J.-C.' },
  { war: "Première guerre d'Illyrie", location: 'Rome antique', date: '229 - 228 av. J.-C.' },
  { war: "Deuxième guerre d'Illyrie", location: 'Rome antique', date: '220 - 219 av. J.-C.' },
  { war: "Troisième guerre d'Illyrie", location: 'Rome antique', date: '168 av. J.-C.' },
  { war: 'Guerres de Macédoine', location: 'Rome antique', date: '215 - 148 av. J.-C.' },
  { war: 'Première guerre de macédonienne', location: 'Rome antique', date: '215 - 205 av. J.-C.' },
  { war: 'Deuxième guerre macédonienne', location: 'Rome antique', date: '200 - 197 av. J.-C.' },
  { war: 'Troisième guerre macédonienne', location: 'Rome antique', date: '172 - 168 av. J.-C.' },
  { war: 'Quatrième guerre macédonienne', location: 'Rome antique', date: '150 - 148 av. J.-C.' },
  { war: 'Guerre séleucide', location: 'Rome antique', date: '192-188 av. J.-C.' },
  { war: 'Guerres celtibères', location: 'Rome antique', date: '181 - 133 av. J.-C.' },
  { war: 'Première guerre celtibère', location: 'Rome antique', date: '181 - 179 av. J.-C.' },
  { war: 'Deuxième guerre celtibère', location: 'Rome antique', date: '154 - 151 av. J.-C.' },
  { war: 'Troisième guerre celtibère', location: 'Rome antique', date: '134 - 133 av. J.-C.' },
  { war: 'Guerre lusitanienne', location: 'Rome antique', date: '155 - 139 av. J.-C.' },
  { war: 'Guerres serviles', location: 'Rome antique', date: '139 - 71 av. J.-C.' },
  { war: 'Première Guerre servile', location: 'Rome antique', date: '139 - 132 av. J.-C.' },
  { war: 'Deuxième Guerre servile', location: 'Rome antique', date: '104 - 103 av. J.-C.' },
  {
    war: 'Troisième Guerre servile ou guerre de Spartacus',
    location: 'Rome antique',
    date: '73 -71 av. J.-C.',
  },
  { war: 'Guerre des Cimbres', location: 'Rome antique', date: '113 - 101 av. J.-C.' },
  { war: 'Guerre de Jugurtha', location: 'Rome antique', date: '111 - 105 av. J.-C.' },
  {
    war: 'Guerres partho-romaines',
    location: 'Rome antique',
    date: '92 av. J.-C. - 217 ap. J.-C.',
  },
  { war: 'Guerre sociale', location: 'Rome antique', date: '91 - 88 av. J.-C.' },
  {
    war: "Guerres de Mithridate Ce lien renvoie vers une page d'homonymie",
    location: 'Rome antique',
    date: '88 - 63 av. J.-C.',
  },
  {
    war: 'Première guerre de Mithridate',
    location: 'Rome antique',
    date: '88 av. J.-C. - 84 av. J.-C.',
  },
  {
    war: 'Deuxième guerre de Mithridate',
    location: 'Rome antique',
    date: '83 av. J.-C. - 81 av. J.-C.',
  },
  {
    war: 'Troisième guerre de Mithridate',
    location: 'Rome antique',
    date: '75 av. J.-C.-63 av. J.-C.',
  },
  {
    war: 'Guerres civiles de la République romaine',
    location: 'Rome antique',
    date: '88 - 30 av. J.-C.',
  },
  {
    war: 'Première guerre civile entre Marius et Sylla',
    location: 'Rome antique',
    date: '88 - 87 av. J.-C.',
  },
  { war: 'Guerre sertorienne', location: 'Rome antique', date: '83 - 72 av. J.-C.' },
  {
    war: 'Seconde guerre civile entre Marius et Sylla',
    location: 'Rome antique',
    date: '82 - 81 av. J.-C.',
  },
  { war: 'Rébellion de Marcus Aemilius Lepidus', location: 'Rome antique', date: '77 av. J.-C.' },
  { war: 'Conjuration de Catilina', location: 'Rome antique', date: '63 - 62 av. J.-C.' },
  { war: 'Guerre civile de César', location: 'Rome antique', date: '49 - 45 av. J.-C.' },
  { war: 'Révolte sicilienne', location: 'Rome antique', date: '44 - 36 av. J.-C.' },
  { war: 'Guerre civile de Modène', location: 'Rome antique', date: '43 av. J.-C.' },
  { war: 'Guerre civile des Libérateurs', location: 'Rome antique', date: '43-42 av. J.-C.' },
  { war: 'Guerre de Pérouse', location: 'Rome antique', date: '41-40 av. J.-C.' },
  {
    war: 'Dernière guerre civile de la République romaine',
    location: 'Rome antique',
    date: '32-30 av. J.-C.',
  },
  { war: 'Guerre des Gaules', location: 'Rome antique', date: '58-51 av. J.-C.' },
  { war: 'Guerres cantabres', location: 'Rome antique', date: '29-19 av. J.-C.' },
  {
    war: "Campagnes d'Auguste en Afrique et en Arabie",
    location: 'Rome antique',
    date: '30 av. J.-C.-6 ap. J.-C.',
  },
  {
    war: "Conquête romaine de la Rhétie et de l'arc alpin",
    location: 'Rome antique',
    date: '16-7 av. J.-C.',
  },
  { war: 'Guerres partho-romaines', location: 'Rome', date: '92 av. J.-C. - 217 ap. J.-C.' },
  { war: 'Guerres judéo-romaines', location: 'Rome', date: '66-135' },
  { war: 'Première guerre judéo-romaine', location: 'Rome', date: '66-73' },
  { war: 'Guerre de Kitos', location: 'Rome', date: '115-117' },
  { war: 'Révolte de Bar Kokhba', location: 'Rome', date: '132-135' },
  { war: 'Conquête de la Grande-Bretagne', location: 'Rome', date: '43-84' },
  {
    war: 'Guerres daciques de Domitien et de Trajan',
    location: 'Rome',
    date: '(85-89) (101-102 et 105-106)',
  },
  { war: 'Guerres daciques de Domitien', location: 'Rome', date: '85-89' },
  { war: 'Guerres daciques de Trajan', location: 'Rome', date: '101-102, 105-106' },
  { war: 'Guerre parthique de Trajan', location: 'Rome', date: '114-117' },
  { war: 'Guerres marcomanes', location: 'Rome', date: '167-188' },
  { war: 'Guerre des Déserteurs', location: 'Rome', date: '185-187' },
  { war: 'Première guerre contre Palmyre', location: 'Rome', date: '272' },
  { war: 'Seconde guerre contre Palmyre', location: 'Rome', date: '273' },
  { war: "Reconquête de l'Empire Gaulois", location: 'Rome', date: '274' },
  { war: 'Guerres des Goths', location: 'Rome', date: 'IIIe-IVe siècle' },
  { war: 'Guerre Han-Xiongnu', location: 'Asie', date: '133 av. J.-C.-89 ap. J.-C.' },
  { war: 'Trois royaumes de Chine', location: 'Asie', date: '220-265' },
  { war: 'Guerre des Vandales', location: 'Afrique', date: '533 - 534' },
  { war: 'Conquête musulmane du Maghreb', location: 'Afrique', date: '642 - 711' },
  { war: 'Guerres perso-byzantines', location: 'Asie (Moyen-Orient)', date: '502 - 628' },
  { war: "Guerre d'Anastase", location: 'Asie (Moyen-Orient)', date: '502 - 506' },
  { war: "Guerre d'Ibérie", location: 'Asie (Moyen-Orient)', date: '526 - 532' },
  { war: 'Guerre lazique', location: 'Asie (Moyen-Orient)', date: '541 - 562' },
  { war: 'Guerre perso-byzantine', location: 'Asie (Moyen-Orient)', date: '572-591 (en)' },
  { war: 'Guerre perso-byzantine', location: 'Asie (Moyen-Orient)', date: '602-628' },
  { war: 'Premières guerres islamiques', location: 'Asie (Moyen-Orient)', date: '' },
  { war: 'Batailles de Mahomet', location: 'Asie (Moyen-Orient)', date: '622 - 632' },
  { war: 'Guerres arabo-byzantines', location: 'Asie (Moyen-Orient)', date: '636 - 750' },
  { war: 'Conquête musulmane de la Perse', location: 'Asie (Moyen-Orient)', date: '637 - 651' },
  { war: 'Guerre de Jinshin', location: 'Asie (Moyen-Orient)', date: '672' },
  { war: "Révolte d'An Lushan", location: 'Asie (Moyen-Orient)', date: '755 - 763' },
  { war: 'Révolte des Zanj', location: 'Asie (Moyen-Orient)', date: '869 - 883' },
  { war: 'Guerre de Burgondie', location: 'Europe', date: '523 - 524' },
  { war: 'Guerre des Goths', location: 'Europe', date: '535–553' },
  { war: "Conquête musulmane de l'Hispanie", location: 'Europe', date: '711 - 732' },
  { war: 'Reconquista', location: 'Europe', date: '718 - 1492' },
  { war: 'Guerre des Saxons', location: 'Europe', date: '772 - 804' },
  { war: 'Guerres des Francs contre les Avars', location: 'Europe', date: '791-799' },
  { war: "Guerre entre Rus' et Byzantins", location: 'Europe', date: '941' },
  { war: 'Guerre bulgaro-byzantine', location: 'Europe', date: '989-1018' },
  { war: 'Invasions normandes', location: 'Europe', date: 'IXe-Xe apr. J.-C.' },
  {
    war: 'La première guerre entre Tikal et Calakmul',
    location: 'Amérique du Sud',
    date: '537 - 572',
  },
  {
    war: 'La deuxième guerre entre Tikal et Calakmul',
    location: 'Amérique du Sud',
    date: '650 - 695',
  },
  {
    war: 'La troisième guerre entre Tikal et Calakmul',
    location: 'Amérique du Sud',
    date: '720- 744',
  },
  { war: 'Septième croisade', location: 'Afrique', date: '1248-1254' },
  { war: 'Huitième croisade', location: 'Afrique', date: '1270' },
  { war: 'Guerres turco-byzantines', location: 'Asie', date: '1048-1453' },
  { war: 'Première croisade', location: 'Asie', date: '1096-1099' },
  { war: 'Deuxième croisade', location: 'Asie', date: '1147-1149' },
  { war: 'Rébellion de Hōgen', location: 'Asie', date: '1156' },
  { war: 'Rébellion de Heiji', location: 'Asie', date: '1159' },
  { war: 'Guerre de Genpei', location: 'Asie', date: '1180-1185' },
  { war: 'Conquêtes mongoles', location: 'Asie', date: '1187 - 1337' },
  { war: 'Troisième croisade', location: 'Asie', date: '1189-1192' },
  { war: 'Cinquième croisade', location: 'Asie', date: '1217-1221' },
  { war: 'Sixième croisade', location: 'Asie', date: '1228-1229' },
  { war: 'Neuvième croisade', location: 'Asie', date: '1271-1272' },
  { war: 'Invasions mongoles du Japon', location: 'Asie', date: '1274 et 1281' },
  { war: 'Campagnes de Tamerlan', location: 'Asie', date: '1383 - 1405' },
  { war: 'Invasion Ming du Dai Viet', location: 'Asie', date: '1407 - 1413' },
  { war: "Guerre d'Ōnin", location: 'Asie', date: '1467-1477' },
  { war: 'Guerre germano-polonaise', location: 'Europe', date: '1002-1018' },
  { war: 'Guerre germano-polonaise', location: 'Europe', date: '1028-1031' },
  { war: "Guerre entre Rus' et Byzantins", location: 'Europe', date: '1043' },
  { war: "Conquête normande de l'Angleterre", location: 'Europe', date: '1066' },
  { war: 'Première croisade', location: 'Europe', date: '1096-1099' },
  { war: 'Guerre germano-polonaise', location: 'Europe', date: '1109' },
  { war: 'Guerre civile anglaise', location: 'Europe', date: '1135-1154' },
  { war: 'Guerres Baussenques en Provence', location: 'Europe', date: '1144-1162' },
  { war: 'Deuxième croisade', location: 'Europe', date: '1147-1149' },
  { war: 'Première Guerre de Cent Ans', location: 'Europe', date: '1159-1299' },
  { war: "Invasion normande de l'Irlande", location: 'Europe', date: '1169-1175' },
  { war: 'Troisième croisade', location: 'Europe', date: '1189-1192' },
  { war: 'Croisades baltes', location: 'Europe', date: '1193-1242' },
  { war: 'Quatrième croisade', location: 'Europe', date: '1202-1204' },
  { war: 'Croisade des albigeois', location: 'Europe', date: '1209-1229' },
  { war: 'Première guerre des Barons', location: 'Europe', date: '1215-1217' },
  { war: 'Guerre de succession de Champagne', location: 'Europe', date: '1216-1222' },
  { war: 'Cinquième croisade', location: 'Europe', date: '1217-1221' },
  { war: 'Sixième croisade', location: 'Europe', date: '1228-1229' },
  { war: 'Guerre des Amis', location: 'Europe', date: '1231-1234' },
  { war: 'Guerre de succession de Flandre et du Hainaut', location: 'Europe', date: '1244-1257' },
  { war: 'Septième croisade', location: 'Europe', date: '1248-1254' },
  { war: 'Guerre de Saint-Sabas', location: 'Europe', date: '1256' },
  { war: 'Guerre écosso-norvégienne', location: 'Europe', date: '1262-1266' },
  { war: 'Seconde guerre des barons', location: 'Europe', date: '1264-1267' },
  { war: 'Huitième croisade', location: 'Europe', date: '1270' },
  { war: 'Neuvième croisade', location: 'Europe', date: '1271-1272' },
  { war: 'Guerre de la vache (Wallonie)', location: 'Europe', date: '(1275-1278)' },
  { war: 'Guerre civile de Navarre', location: 'Europe', date: '1276' },
  {
    war: 'Guerre de succession du Limbourg, bataille de Worringen',
    location: 'Europe',
    date: '1283-1288',
  },
  { war: "Première guerre d'indépendance de l'Écosse", location: 'Europe', date: '1296-1328' },
  { war: 'Guerre des Awans et des Waroux', location: 'Europe', date: '1297-1335' },
  { war: 'Révolte des Karls', location: 'Europe', date: '1323-1328' },
  { war: 'Guerre des quatre seigneurs', location: 'Europe', date: '1324-1326' },
  { war: 'Guerre du seau volé', location: 'Europe', date: '1325-1325' },
  { war: "Deuxième guerre d'indépendance de l'Écosse", location: 'Europe', date: '1332-1357' },
  { war: 'Guerre des Deux Pierre', location: 'Europe', date: '1361-1363' },
  { war: 'Révolution haïtienne', location: 'Europe', date: '1791-1804' },
  { war: 'Guerre russo-tlingit', location: 'Europe', date: '1799-1804' },
  { war: 'Guerre russo-persane', location: 'Asie', date: '1722-1723' },
  { war: 'Guerres carnatiques', location: 'Asie', date: '(1744-1748) et (1749-1763)' },
  { war: "Campagne de l'Oudh", location: 'Asie', date: '1760-1764' },
  { war: 'Guerres de Mysore', location: 'Asie', date: '1767-1769, 1784-1790, 1790-1792 et 1799' },
  {
    war: 'Guerres anglo-marathes',
    location: 'Asie',
    date: '(1776-1782), (1803-1806) et (1817-1819)',
  },
  { war: 'Campagne de Ceylan', location: 'Asie', date: '(1795-1818)' },
  { war: 'Guerres anglo-néerlandaises', location: 'Europe', date: '1652-1784' },
  { war: 'Quatrième guerre anglo-néerlandaise', location: 'Europe', date: '1780-1784' },
  { war: 'Grande Guerre du Nord', location: 'Europe', date: '1700-1721' },
  { war: "Guerre de Succession d'Espagne", location: 'Europe', date: '1701-1713' },
  { war: 'Guerre des Cévennes ou guerre des Camisards', location: 'Europe', date: '1702-1704' },
  { war: 'Guerre russo-turque', location: 'Europe', date: '1710-1711' },
  { war: 'Rébellions jacobites', location: 'Europe', date: '1715, 1719, 1744, 1745, 1759' },
  { war: 'Guerre vénéto-austro-ottomane', location: 'Europe', date: '1716-1718' },
  { war: 'Guerre de la Quadruple-Alliance', location: 'Europe', date: '1718-1720' },
  { war: 'Guerre anglo-espagnole', location: 'Europe', date: '1727-1729' },
  { war: 'Guerre de Succession de Pologne', location: 'Europe', date: '1733-1738' },
  { war: 'Guerre austro-russo-turque', location: 'Europe', date: '1735-1739' },
  { war: "Guerre de Succession d'Autriche", location: 'Europe', date: '1740-1748' },
  {
    war: 'Guerres de Silésie',
    location: 'Europe',
    date: '(1740-1742), (1744-1745) et (1756-1763)',
  },
  { war: 'Guerre des Chapeaux ou Guerre russo-suédoise', location: 'Europe', date: '1741-1743' },
  { war: 'Guerre de Sept Ans', location: 'Europe', date: '1756-1763' },
  { war: 'Guerre hispano-portugaise', location: 'Europe', date: '1762-1763' },
  { war: 'Guerre russo-turque', location: 'Europe', date: '1768-1774' },
  { war: 'Guerre des Paysans russes', location: 'Europe', date: '1773-1775' },
  {
    war: 'Guerre de Succession de Bavière ou guerre des pommes de terre',
    location: 'Europe',
    date: '1778-1779',
  },
  { war: 'Guerre russo-suédoise', location: 'Europe', date: '1788-1790' },
  { war: 'Guerre de la Marmite', location: 'Europe', date: '1785' },
  { war: 'Guerre russo-turque', location: 'Europe', date: '1787-1792' },
  { war: 'Guerres de la Révolution', location: 'Europe', date: '1792-1802' },
  { war: 'Guerre de la Première Coalition', location: 'Europe', date: '1792-1797' },
  { war: 'Guerre du Roussillon', location: 'Europe', date: '1793-1795' },
  { war: "Campagne d'Italie", location: 'Europe', date: '1796-1797' },
  { war: 'Guerre de Vendée', location: 'Europe', date: '1793-1796' },
  { war: 'Chouannerie', location: 'Europe', date: '1794-1800' },
  { war: 'Rébellion irlandaise', location: 'Europe', date: '1798' },
  { war: 'Guerre des paysans', location: 'Europe', date: '(Belgique et Luxembourg) 1798' },
  { war: 'Guerre de la Deuxième Coalition', location: 'Europe', date: '1799-1801' },
  { war: "Campagne d'Égypte", location: 'Europe', date: '1798-1800' },
  { war: "Campagne d'Italie", location: 'Europe', date: '1799-1800' },
  { war: 'Quasi guerre', location: 'Europe', date: '1798-1800' },
  { war: 'Guerre de Sept Ans', location: 'Monde', date: '1756-1763' },
  { war: 'Guerre de la Conquête', location: 'Monde', date: '1756-1760' },
  { war: 'Le Mfecane de Chaka contre les peuples environnants', location: 'Afrique', date: '' },
  {
    war: 'Les 9 guerres cafres entre Afrikaners et Xhosas',
    location: 'Afrique',
    date: '1800-1900',
  },
  { war: 'Guerre de Tripoli', location: 'Afrique', date: '1801-1805' },
  { war: "Le Jihad d'Ousman dan fodio", location: 'Afrique', date: '1805-1850' },
  { war: 'Seconde guerre barbaresque', location: 'Afrique', date: '1815' },
  { war: 'La guerre anglo-égyptienne contre le Mahdi au Soudan', location: 'Afrique', date: '' },
  { war: 'Guerres anglo-ashanti', location: 'Afrique', date: '1824-1901' },
  { war: 'Guerre entre la France et le Trarza', location: 'Afrique', date: '1825' },
  { war: "Conquête de l'Algérie par la France", location: 'Afrique', date: '1830-1902' },
  { war: 'Guerre franco-marocaine', location: 'Afrique', date: '1844' },
  { war: "Guerre d'Afrique ou Guerre hispano-marocaine", location: 'Afrique', date: '1859-1860' },
  { war: 'Guerre égypto-éthiopienne', location: 'Afrique', date: '1874-1876' },
  { war: 'Guerre anglo-zouloue', location: 'Afrique', date: '1879' },
  { war: 'Première guerre des Boers', location: 'Afrique', date: '1879-1880' },
  {
    war: "Guerre des Mahdistes, Bataille d'Omdurman",
    location: 'Afrique',
    date: '(1881-1898) (1898)',
  },
  { war: 'Expédition de Madagascar', location: 'Afrique', date: '1881-1895' },
  { war: 'Guerre anglo-égyptienne', location: 'Afrique', date: '1882' },
  { war: 'Première guerre franco-malgache', location: 'Afrique', date: '1883-1885' },
  { war: 'Première guerre du Dahomey', location: 'Afrique', date: '1890' },
  { war: 'Seconde guerre du Dahomey', location: 'Afrique', date: '1892-1894' },
  {
    war: "Campagnes de l'État indépendant du Congo contre les Arabo-Swahilis",
    location: 'Afrique',
    date: '1892-1894',
  },
  { war: 'Première guerre italo-éthiopienne', location: 'Afrique', date: '1895-1896' },
  { war: 'Bombardement de Zanzibar', location: 'Afrique', date: '1896' },
  { war: 'Deuxième Guerre des Boers', location: 'Afrique', date: '1899-1902' },
  { war: 'Djihad de Mad Mullah', location: 'Afrique', date: '1899-1920' },
  { war: 'Invasions britanniques du Rio de la Plata', location: 'Amérique', date: '1806-1807' },
  { war: "Guerres d'indépendance en Amérique du Sud", location: 'Amérique', date: '1809-1826' },
  { war: "Guerre d'indépendance de la Colombie", location: 'Amérique', date: '1810-1819' },
  { war: "Guerre d'indépendance du Mexique", location: 'Amérique', date: '1810-1821' },
  { war: "Guerre d'indépendance du Venezuela", location: 'Amérique', date: '1810-1823' },
  { war: "Guerre d'indépendance d'Argentine", location: 'Amérique', date: '1810-1825' },
  { war: "Guerre d'indépendance du Pérou", location: 'Amérique', date: '1811-1824' },
  { war: "Guerre d'indépendance du Chili", location: 'Amérique', date: '1813-1826' },
  { war: "Guerre d'indépendance d'Équateur", location: 'Amérique', date: '1820-1823' },
  { war: 'Guerre de Tecumseh', location: 'Amérique', date: '1811-1813' },
  { war: "Seconde guerre d'indépendance américaine", location: 'Amérique', date: '1812-1814' },
  { war: 'Guerres civiles argentines', location: 'Amérique', date: '1814-1880' },
  {
    war: 'Guerres séminoles',
    location: 'Amérique',
    date: '(1817-1818), (1835-1842) et (1855-1858)',
  },
  { war: "Guerre d'indépendance du Brésil", location: 'Amérique', date: '1822-1823' },
  { war: 'Guerre de Cisplatine', location: 'Amérique', date: '1825-1828' },
  { war: 'Guerre Grande Colombie-Pérou', location: 'Amérique', date: '1828-1829' },
  { war: 'Guerre colombo-équatorienne', location: 'Amérique', date: '1832' },
  { war: 'Guerre de Black Hawk', location: 'Amérique', date: '1832' },
  { war: 'Révolution texane', location: 'Amérique', date: '1835-1836' },
  { war: 'Guerre des Farrapos', location: 'Amérique', date: '1835-1845' },
  { war: 'Rébellion des Patriotes au Canada', location: 'Amérique', date: '' },
  { war: 'Guerre des pâtisseries', location: 'Amérique', date: '1838' },
  { war: "Guerre d'Aroostook", location: 'Amérique', date: '1838-1839' },
  { war: 'Grande guerre', location: 'Amérique', date: '(Uruguay) (1839-1851)' },
  { war: 'Guerres civiles colombiennes', location: 'Amérique', date: '1839-1902' },
  { war: 'Guerre des suprêmes', location: 'Amérique', date: '1839-1842' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1851' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1854' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1860-1862' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1876-1877' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1885' },
  { war: 'Guerre civile colombienne', location: 'Amérique', date: '1895' },
  { war: 'Guerre des Mille Jours', location: 'Amérique', date: '1899-1902' },
  { war: 'Guerre américano-mexicaine', location: 'Amérique', date: '1846-1848' },
  { war: 'Guerre Cayuse', location: 'Amérique', date: '1847-1855' },
  { war: 'Guerre Jicarilla', location: 'Amérique', date: '1849-1855' },
  { war: 'Guerre de la Plata', location: 'Amérique', date: '1851-1852' },
  { war: 'Guerres des Rogue River', location: 'Amérique', date: '' },
  {
    war: 'Expéditions de William Walker en Amérique centrale',
    location: 'Amérique',
    date: '1853-1860',
  },
  { war: 'Campagne nationale du Costa Rica', location: 'Amérique', date: '1856-1857' },
  { war: 'Guerre de Wakarusa', location: 'Amérique', date: '1855' },
  { war: 'Guerre Yakima', location: 'Amérique', date: '1855-1858' },
  { war: 'Guerre de Réforme', location: 'Amérique', date: '1857-1861' },
  {
    war: "Conflits frontaliers entre le Pérou et l'Équateur",
    location: 'Amérique',
    date: '1858-1998',
  },
  { war: 'Guerre péruano-équatorienne', location: 'Amérique', date: '1858' },
  { war: 'Guerre fédérale', location: 'Amérique', date: '1859-1863' },
  { war: 'Guerre de Sécession aux États-Unis', location: 'Amérique', date: '1861-1865' },
  { war: 'Expédition du Mexique', location: 'Amérique', date: '1861-1867' },
  {
    war: "Guerre de Restauration ou deuxième guerre d'indépendance",
    location: 'Amérique',
    date: '1863-1865',
  },
  { war: 'Guerre du Colorado', location: 'Amérique', date: '1863-1865' },
  { war: 'Guerre hispano-sud-américaine', location: 'Amérique', date: '1864-1883' },
  { war: 'Guerre de Red Cloud', location: 'Amérique', date: '1866-1868' },
  { war: 'Guerre des Dix Ans à Cuba', location: 'Amérique', date: '1868-1878' },
  {
    war: 'Guerre de la Triple-Alliance ou Guerre du Paraguay',
    location: 'Amérique',
    date: '1864-1870',
  },
  { war: 'Conquête du Désert', location: 'Amérique', date: '1869-1888' },
  { war: 'Guerre de la rivière Rouge', location: 'Amérique', date: '1874-1875' },
  { war: 'Guerre des Black Hills', location: 'Amérique', date: '1876-1877' },
  { war: 'Guerre des chasseurs de bisons', location: 'Amérique', date: '1876-1877' },
  { war: 'Guerre des Nez-Percés', location: 'Amérique', date: '1877' },
  { war: 'Guerre des Bannocks', location: 'Amérique', date: '1878' },
  { war: 'Guerre des Sheepeaters', location: 'Amérique', date: '1879' },
  { war: 'Petite Guerre', location: 'Amérique', date: '1879-1880' },
  { war: 'Guerre de Victorio', location: 'Amérique', date: '1879-1881' },
  { war: 'Guerre du Pacifique', location: 'Amérique', date: '1879-1884' },
  { war: 'Rébellion du Nord-Ouest', location: 'Amérique', date: '1885' },
  { war: 'Deuxième Guerre civile chilienne', location: 'Amérique', date: '1891' },
  { war: "Guerre d'indépendance cubaine", location: 'Amérique', date: '1895-1898' },
  { war: 'Guerre hispano-américaine', location: 'Amérique', date: '1898' },
  { war: 'Guerre des Mille Jours', location: 'Amérique', date: '1899-1903' },
  { war: 'Deuxième guerre anglo-marathe', location: 'Asie et Moyen-Orient', date: '1803-1804' },
  { war: 'Guerre russo-persane', location: 'Asie et Moyen-Orient', date: '1804-1813' },
  { war: 'Guerre anglo-néerlandaise de Java', location: 'Asie et Moyen-Orient', date: '1810-1811' },
  { war: 'Guerre anglo-népalaise', location: 'Asie et Moyen-Orient', date: '1814-1816' },
  { war: 'Guerre des Padri', location: 'Asie et Moyen-Orient', date: '1821-1837' },
  { war: 'Guerres anglo-birmanes', location: 'Asie et Moyen-Orient', date: '1824-1885' },
  { war: 'Guerre de Bone', location: 'Asie et Moyen-Orient', date: '1825' },
  { war: 'Guerre de Java', location: 'Asie et Moyen-Orient', date: '1825-1830' },
  { war: 'Guerre russo-persane', location: 'Asie et Moyen-Orient', date: '1826-1828' },
  {
    war: 'Première, deuxième et troisième guerre anglo-afghane',
    location: 'Asie et Moyen-Orient',
    date: '(1839-1842), (1878-1880) et (1919)',
  },
  {
    war: 'Guerres anglo-sikhs',
    location: 'Asie et Moyen-Orient',
    date: '(1845-1846) et (1848-1849)',
  },
  { war: 'Guerre anglo-perse', location: 'Asie et Moyen-Orient', date: '1856-1857' },
  { war: 'Révolte des Cipayes', location: 'Asie et Moyen-Orient', date: '1857-1858' },
  { war: 'Guerre du Hedjaz', location: 'Asie et Moyen-Orient', date: '1812-1819' },
  { war: 'Première Guerre égypto-ottomane', location: 'Asie et Moyen-Orient', date: '1831-1833' },
  { war: 'Deuxième Guerre égypto-ottomane', location: 'Asie et Moyen-Orient', date: '1839-1840' },
  { war: "Première guerre de l'opium", location: 'Asie et Moyen-Orient', date: '1839-1842' },
  { war: 'Révolte des Taiping', location: 'Asie et Moyen-Orient', date: '1850-1864' },
  { war: "Seconde guerre de l'opium", location: 'Asie et Moyen-Orient', date: '1856-1858' },
  { war: 'Guerre des Païutes', location: 'Asie et Moyen-Orient', date: '1860' },
  { war: 'Guerre des Sioux', location: 'Asie et Moyen-Orient', date: '1862' },
  { war: 'Révolte des Dounganes', location: 'Asie et Moyen-Orient', date: '1862-1877' },
  { war: 'Guerre de Boshin', location: 'Asie et Moyen-Orient', date: '1868-1869' },
  { war: 'Guerre des Modocs', location: 'Asie et Moyen-Orient', date: '1872-1873' },
  { war: "Guerre d'Aceh", location: 'Asie et Moyen-Orient', date: '1873-1904' },
  { war: 'Rébellion de Satsuma', location: 'Asie et Moyen-Orient', date: '1877' },
  { war: 'Guerre franco-chinoise', location: 'Asie et Moyen-Orient', date: '1881-1885' },
  { war: 'Guerre franco-siamoise', location: 'Asie et Moyen-Orient', date: '1893' },
  { war: 'Première guerre sino-japonaise', location: 'Asie et Moyen-Orient', date: '1894-1895' },
  { war: 'Révolte des Boxers', location: 'Asie et Moyen-Orient', date: '1899-1901' },
  { war: 'Guerre américano-philippine', location: 'Asie et Moyen-Orient', date: '1899-1902' },
  { war: 'Guerres napoléoniennes', location: 'Europe', date: '1803-1815' },
  { war: 'Guerre des Oranges', location: 'Europe', date: '1801' },
  { war: 'Guerres anglaises (Scandinavie)', location: 'Europe', date: '1801-1814' },
  { war: 'Guerre des canonnières', location: 'Europe', date: '1807-1814' },
  { war: 'Guerre de la Troisième Coalition', location: 'Europe', date: '1805-1806' },
  { war: 'Guerre de la Quatrième Coalition', location: 'Europe', date: '1806-1808' },
  { war: "Guerre d'indépendance espagnole", location: 'Europe', date: '1808-1813' },
  { war: 'Guerre de Finlande', location: 'Europe', date: '1808-1809' },
  { war: 'Guerre de la Cinquième Coalition', location: 'Europe', date: '1809' },
  { war: 'Guerre de la Sixième Coalition', location: 'Europe', date: '1812-1814' },
  { war: 'Campagne de Russie', location: 'Europe', date: '1812' },
  { war: 'Campagne de France', location: 'Europe', date: '1814' },
  { war: 'Guerre de la Septième Coalition', location: 'Europe', date: '1815' },
  { war: 'Campagne de Belgique', location: 'Europe', date: '1815' },
  { war: 'Guerre napolitaine', location: 'Europe', date: '' },
  { war: 'Guerre de Vendée et Chouannerie', location: 'Europe', date: '1815' },
  { war: 'Guerre russo-turque', location: 'Europe', date: '1806-1812' },
  { war: 'Guerre suédo-norvégienne', location: 'Europe', date: '1814' },
  { war: 'Premier soulèvement serbe', location: 'Europe', date: '1804-1813' },
  { war: 'Second soulèvement serbe', location: 'Europe', date: '1815-1817' },
  { war: 'Guerre du Caucase', location: 'Europe', date: '1816-1864' },
  { war: "Guerre d'indépendance grecque", location: 'Europe', date: '1821-1828' },
  { war: "Expédition d'Espagne", location: 'Europe', date: '1823' },
  { war: 'Guerre russo-turque', location: 'Europe', date: '1828-1829' },
  { war: 'Guerre civile portugaise', location: 'Europe', date: '1828-1834' },
  { war: 'Guerre des Demoiselles', location: 'Europe', date: '1829-1832' },
  { war: 'Insurrection de novembre 1830 en Pologne', location: 'Europe', date: '1830' },
  { war: 'Révolution belge', location: 'Europe', date: '1830-1831' },
  { war: 'Guerre de Vendée et Chouannerie', location: 'Europe', date: '1832' },
  { war: 'Première guerre carliste', location: 'Europe', date: '1833-1840' },
  { war: 'Deuxième guerre carliste', location: 'Europe', date: '1846-1849' },
  { war: 'Guerre du Sonderbund', location: 'Europe', date: '1847' },
  { war: "Première guerre d'indépendance italienne", location: 'Europe', date: '1848-1849' },
  { war: 'Première guerre de Schleswig', location: 'Europe', date: '1848-1851' },
  { war: 'Guerre de Crimée', location: 'Europe', date: '1853-1856' },
  {
    war: "Campagne d'Italie, ou seconde guerre d'indépendance italienne (Risorgimento)",
    location: 'Europe',
    date: '1859-1860',
  },
  { war: 'Insurrection polonaise', location: 'Europe', date: '1861-1864' },
  { war: 'Seconde guerre des Duchés', location: 'Europe', date: '1864' },
  {
    war: "Troisième guerre d'Indépendance italienne (Risorgimento)",
    location: 'Europe',
    date: '1865-1866',
  },
  { war: 'Guerre austro-prussienne ou Guerre des sept semaines', location: 'Europe', date: '1866' },
  {
    war: 'Guerre franco-allemande ou franco-prussienne, ou guerre de 70',
    location: 'Europe',
    date: '1870-1871',
  },
  { war: 'Commune de Paris', location: 'Europe', date: '1871' },
  { war: 'Troisième guerre carliste Carlisme', location: 'Europe', date: '1872-1876' },
  {
    war: 'Guerre russo-turque (dixième guerre russo-turque)',
    location: 'Europe',
    date: '1877-1878',
  },
  { war: 'Guerre serbo-bulgare', location: 'Europe', date: '1885-1886' },
  { war: 'Guerre gréco-turque', location: 'Europe', date: '1897' },
  { war: 'Guerre italo-turque', location: 'Afrique', date: '1911-1912' },
  { war: 'Rébellion touarègue', location: 'Afrique', date: '' },
  { war: 'Révolte de Kaocen au Niger', location: 'Afrique', date: '1916-1917' },
  { war: 'Guerre du Rif', location: 'Afrique', date: '1921-1926' },
  { war: "Pacification de la Libye (Résistance d'Omar Al Mokhtar)", location: 'Afrique', date: '' },
  { war: 'Seconde guerre italo-éthiopienne', location: 'Afrique', date: '1935-1936' },
  { war: 'Résistance éthiopienne', location: 'Afrique', date: '1936-1941' },
  { war: 'Guerre du désert', location: 'Afrique', date: '1942-1945' },
  { war: "Campagne d'Afrique de l'Est", location: 'Afrique', date: '1940' },
  { war: 'Campagne du Gabon', location: 'Afrique', date: '1940' },
  { war: "Guerre d'Algérie", location: 'Afrique', date: '1962' },
  { war: 'Révolution mexicaine', location: 'Amérique du Sud', date: '1910-1920' },
  { war: 'Guerre des Cristeros au Mexique', location: 'Amérique du Sud', date: '1926-1929' },
  { war: 'Guerre colombo-péruvienne', location: 'Amérique du Sud', date: '1932-1933' },
  { war: 'Guerre du Chaco', location: 'Amérique du Sud', date: '1932-1935' },
  {
    war: "Conflits frontaliers entre le Pérou et l'Équateur",
    location: 'Amérique du Sud',
    date: '1858-1998',
  },
  { war: 'Guerre péruano-équatorienne', location: 'Amérique du Sud', date: '1941' },
  {
    war: "Unification de l'Arabie saoudite",
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1902-1932',
  },
  { war: 'Guerre russo-japonaise', location: 'Asie, Océanie et Moyen-Orient', date: '1904-1905' },
  { war: 'Révolte arabe', location: 'Asie, Océanie et Moyen-Orient', date: '1916-1918' },
  {
    war: 'Troisième guerre anglo-afghane',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1919',
  },
  {
    war: 'Grande révolte syrienne ou guerre des Druzes',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1925-1926',
  },
  { war: 'Guerre civile chinoise', location: 'Asie, Océanie et Moyen-Orient', date: '1927-1950' },
  { war: 'Guerre des plaines centrales', location: 'Asie, Océanie et Moyen-Orient', date: '1930' },
  { war: 'Guerre des émeus', location: 'Asie, Océanie et Moyen-Orient', date: '1932' },
  {
    war: 'Grande révolte arabe de 1936-1939 en Palestine mandataire',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1936-1939',
  },
  {
    war: 'Seconde guerre sino-japonaise',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1937-1945',
  },
  { war: 'Bataille de Khalkhin Gol', location: 'Asie, Océanie et Moyen-Orient', date: '1939' },
  { war: 'Guerre anglo-irakienne', location: 'Asie, Océanie et Moyen-Orient', date: '1941' },
  { war: 'Campagne de Syrie', location: 'Asie, Océanie et Moyen-Orient', date: '1941' },
  {
    war: "Invasion anglo-soviétique de l'Iran",
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1941',
  },
  { war: 'Guerre du Pacifique', location: 'Asie, Océanie et Moyen-Orient', date: '' },
  {
    war: 'Guerre franco-thaïlandaise ou franco-siamoise',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1940-1941',
  },
  { war: 'Campagne de Birmanie', location: 'Asie, Océanie et Moyen-Orient', date: '1942-1945' },
  {
    war: 'Guerres baloutches',
    location: 'Asie, Océanie et Moyen-Orient',
    date: '1945 à nos jours',
  },
  { war: 'Guerre italo-turque', location: 'Europe', date: '1911-1912' },
  { war: 'Première guerre balkanique', location: 'Europe', date: '1912-1913' },
  { war: 'Deuxième guerre balkanique', location: 'Europe', date: '1913' },
  { war: 'Campagne du Caucase', location: 'Europe', date: '1914-1917' },
  { war: "Front de l'Ouest", location: 'Europe', date: '1914-1918' },
  { war: "Front de l'Est", location: 'Europe', date: '1914-1917' },
  { war: 'Front italien', location: 'Europe', date: '1915-1918' },
  { war: "Front d'Orient", location: 'Europe', date: '1915-1918' },
  { war: 'Insurrection de Pâques', location: 'Europe', date: '1916' },
  { war: 'Guerre civile russe', location: 'Europe', date: '1918-1921' },
  { war: 'Guerre soviéto-turque', location: 'Europe', date: '1917-1918' },
  {
    war: 'Intervention alliée pendant la guerre civile russe',
    location: 'Europe',
    date: '1918-1922',
  },
  { war: 'Intervention en Russie septentrionale', location: 'Europe', date: '1918-1920' },
  { war: 'Intervention en Sibérie', location: 'Europe', date: '1918-1922' },
  { war: 'Invasion soviétique de la Géorgie', location: 'Europe', date: '1921' },
  { war: 'Guerre civile finlandaise', location: 'Europe', date: '1918' },
  { war: 'Guerre arméno-géorgienne', location: 'Europe', date: '1918' },
  { war: "Guerre d'indépendance de l'Estonie", location: 'Europe', date: '1918-1920' },
  { war: "Guerre d'indépendance de la Lettonie", location: 'Europe', date: '1918-1920' },
  { war: "Guerres d'indépendance lituaniennes", location: 'Europe', date: '1918-1920' },
  { war: 'Guerre polono-lituanienne', location: 'Europe', date: '1920' },
  { war: 'Guerre hongro-roumaine', location: 'Europe', date: '1919' },
  { war: "Guerre d'indépendance irlandaise", location: 'Europe', date: '1919-1921' },
  { war: 'Guerre soviéto-polonaise', location: 'Europe', date: '1920-1921' },
  { war: "Guerre d'indépendance turque", location: 'Europe', date: '1919-1923' },
  { war: 'Campagne de Cilicie', location: 'Europe', date: '1918-1921' },
  { war: 'Guerre gréco-turque', location: 'Europe', date: '1919-1922' },
  { war: 'Guerre arméno-turque', location: 'Europe', date: '1920' },
  { war: 'Guerre civile turque', location: 'Europe', date: '1920' },
  { war: 'Guerre civile irlandaise', location: 'Europe', date: '1922-1923' },
  { war: 'Guerre civile autrichienne', location: 'Europe', date: '1934' },
  { war: 'Guerre civile espagnole', location: 'Europe', date: '1936-1939' },
  { war: 'Guerre slovaquo-hongroise', location: 'Europe', date: '1939' },
  { war: "Front de l'Ouest", location: 'Europe', date: '1939-1945' },
  { war: "Front de l'Est", location: 'Europe', date: '1939-1945' },
  { war: "Guerre d'Hiver", location: 'Europe', date: '1939-1940' },
  { war: 'Guerre de Continuation', location: 'Europe', date: '1941-1944' },
  { war: 'Guerre de Continuation', location: 'Europe', date: '1941-1944' },
  { war: 'Guerre de Laponie', location: 'Europe', date: '1944-1945' },
  { war: 'Insurrection malgache', location: 'Afrique', date: '1947' },
  { war: 'Révolte des Mau Mau', location: 'Afrique', date: '1952-1956' },
  { war: "Guerre d'Algérie", location: 'Afrique', date: '1954-1962' },
  { war: 'Première guerre civile soudanaise', location: 'Afrique', date: '1955-1972' },
  { war: 'Crise du canal de Suez', location: 'Afrique', date: '1956' },
  { war: "Guerre d'Ifni", location: 'Afrique', date: '1957-1958' },
  { war: 'Crise congolaise', location: 'Afrique', date: '1960-1965' },
  { war: 'Opération des Nations unies au Congo', location: 'Afrique', date: '1960-1964' },
  { war: 'Crise de Bizerte', location: 'Afrique', date: '1961' },
  { war: 'Guerres coloniales portugaises', location: 'Afrique', date: '1961-1974' },
  { war: "Guerre d'indépendance de l'Angola", location: 'Afrique', date: '1961-1974' },
  { war: "Guerre d'indépendance de la Guinée-Bissau", location: 'Afrique', date: '1963-1974' },
  { war: "Guerre d'indépendance du Mozambique", location: 'Afrique', date: '1964-1974' },
  { war: "Guerre d'indépendance de l'Érythrée", location: 'Afrique', date: '1962-1991' },
  { war: 'Rébellion touarègue', location: 'Afrique', date: '' },
  { war: 'Rébellion touarègue au Mali', location: 'Afrique', date: '1963-1964' },
  { war: 'Rébellion touarègue au Mali et au Niger', location: 'Afrique', date: '1990-1996' },
  { war: 'Guerre des Sables', location: 'Afrique', date: '1963' },
  { war: 'Guerre de la frontière sud-africaine', location: 'Afrique', date: '1965-1988' },
  { war: 'Guerre du Tchad', location: 'Afrique', date: '1965-1994' },
  { war: 'Guerre civile tchadienne', location: 'Afrique', date: '1965-1979' },
  { war: 'Conflit tchado-libyen', location: 'Afrique', date: '1978-1987' },
  { war: 'Guerre civile tchadienne', location: 'Afrique', date: '1979-1994' },
  { war: 'Guerre civile au Nigeria ou guerre du Biafra', location: 'Afrique', date: '1967-1970' },
  { war: 'Guerre du Bush de Rhodésie du Sud', location: 'Afrique', date: '1972-1979' },
  { war: 'Guerres civiles en Éthiopie', location: 'Afrique', date: '1974-1991' },
  { war: 'Guerre du Sahara occidental', location: 'Afrique', date: '1975-1991' },
  { war: 'Guerre civile du Mozambique', location: 'Afrique', date: '1975-1992' },
  { war: 'Guerre civile angolaise', location: 'Afrique', date: '1975-2002' },
  { war: "Guerre d'indépendance du Cabinda", location: 'Afrique', date: '1975-?' },
  { war: "Raid d'Entebbe", location: 'Afrique', date: '1976' },
  { war: 'Première guerre du Shaba', location: 'Afrique', date: '1977' },
  { war: 'Guerre égypto-libyenne', location: 'Afrique', date: '1977' },
  { war: "Guerre de l'Ogaden", location: 'Afrique', date: '1977-1978' },
  { war: 'Deuxième guerre du Shaba', location: 'Afrique', date: '1978' },
  { war: 'Guerre ougando-tanzanienne', location: 'Afrique', date: '1978-1979' },
  { war: 'Guerre de brousse en Ouganda', location: 'Afrique', date: '1981-1986' },
  { war: 'Seconde guerre civile soudanaise', location: 'Afrique', date: '1983-2005' },
  { war: "Guerre de la Bande d'Agacher ou guerre de Noël", location: 'Afrique', date: '1985' },
  { war: 'Opération Jambe de bois', location: 'Afrique', date: '1985' },
  { war: 'Opération El Dorado Canyon', location: 'Afrique', date: '1986' },
  { war: "Insurrection de l'Armée de Résistance du Seigneur", location: 'Afrique', date: '1987-?' },
  { war: 'Première et deuxième guerre civile du Libéria', location: 'Afrique', date: '1989-2003' },
  { war: 'Guerre civile rwandaise', location: 'Afrique', date: '1990-1993' },
  { war: 'Guerre civile djiboutienne', location: 'Afrique', date: '1991-1994' },
  { war: 'Guerre civile sierra-léonaise', location: 'Afrique', date: '1991-2002' },
  { war: 'Guerre civile somalienne', location: 'Afrique', date: '1991-?' },
  { war: 'Opération Restore Hope', location: 'Afrique', date: '1993' },
  { war: "Guerre civile d'Algérie", location: 'Afrique', date: '1992-2002' },
  { war: 'Guerre civile burundaise', location: 'Afrique', date: '1993-2005' },
  { war: 'Génocide des Tutsis au Rwanda', location: 'Afrique', date: '1994' },
  { war: 'Conflit de Caprivi', location: 'Afrique', date: '1994-1999' },
  { war: 'Première guerre du Congo', location: 'Afrique', date: '1996-1997' },
  {
    war: 'Insurrection des Forces démocratiques alliées (FDA)',
    location: 'Afrique',
    date: '1996-?',
  },
  { war: 'Guerre civile du Congo-Brazzaville', location: 'Afrique', date: '1997-1999' },
  { war: 'Opération Infinite Reach', location: 'Afrique', date: '1998' },
  { war: 'Guerre civile de Guinée-Bissau', location: 'Afrique', date: '1998-1999' },
  { war: 'Deuxième guerre du Congo', location: 'Afrique', date: '1998-2003' },
  { war: "Conflit d'Ituri", location: 'Afrique', date: '1999-?' },
  { war: 'Guerre Ethiopie-Erythrée', location: 'Afrique', date: '1998-2000' },
  { war: 'Guerre civile paraguayenne', location: 'Amérique du Sud', date: '1947' },
  { war: 'Guerre civile costaricaine', location: 'Amérique du Sud', date: '1948' },
  { war: 'La Violencia en Colombie', location: 'Amérique du Sud', date: '1948-1953' },
  { war: 'Révolution cubaine', location: 'Amérique du Sud', date: '1956-1959' },
  { war: 'Guerre civile au Guatemala', location: 'Amérique du Sud', date: '1960-1996' },
  { war: 'Débarquement de la baie des Cochons', location: 'Amérique du Sud', date: '1961' },
  { war: 'Révolution sandiniste (Nicaragua)', location: 'Amérique du Sud', date: '1961-1990' },
  { war: 'Conflit armé colombien', location: 'Amérique du Sud', date: '1964-?' },
  { war: 'Guérilla des FARC en Colombie', location: 'Amérique du Sud', date: '1964-?' },
  {
    war: 'Seconde occupation de la République dominicaine par les États-Unis',
    location: 'Amérique du Sud',
    date: '1965-1966',
  },
  {
    war: 'Guerre de cent heures ou "guerre du football"',
    location: 'Amérique du Sud',
    date: '1969',
  },
  { war: 'Guerre civile du Salvador', location: 'Amérique du Sud', date: '1979-1992' },
  { war: 'Guérilla du "Sentier lumineux" au Pérou', location: 'Amérique du Sud', date: '1980-?' },
  {
    war: "Conflits frontaliers entre le Pérou et l'Équateur",
    location: 'Amérique du Sud',
    date: '1858-1998',
  },
  { war: 'Guerre du Paquisha', location: 'Amérique du Sud', date: '1981' },
  { war: 'Guerre du Cenepa', location: 'Amérique du Sud', date: '1995' },
  { war: 'Guerre des Malouines', location: 'Amérique du Sud', date: '1982' },
  { war: 'Invasion de la Grenade', location: 'Amérique du Sud', date: '1983' },
  { war: 'Invasion du Panama par les États-Unis', location: 'Amérique du Sud', date: '1989' },
  {
    war: 'Intervention militaire en Haïti sous la conduite des États-Unis',
    location: 'Amérique du Sud',
    date: '1994',
  },
  { war: 'Révolte au Chiapas', location: 'Amérique du Sud', date: '1994-1996' },
  {
    war: "Révolution nationale indonésienne ou guerre d'indépendance indonésienne",
    location: 'Asie et Moyen-Orient',
    date: '1945-1949',
  },
  { war: 'Crise irano-soviétique', location: 'Asie et Moyen-Orient', date: '1945-1946' },
  { war: "Guerre d'Indochine", location: 'Asie et Moyen-Orient', date: '1946-1954' },
  {
    war: 'Guerre civile de 1947-1948 en Palestine mandataire',
    location: 'Asie et Moyen-Orient',
    date: '1947-1948',
  },
  { war: 'Partition des Indes', location: 'Asie et Moyen-Orient', date: '1947' },
  { war: 'Première Guerre indo-pakistanaise', location: 'Asie et Moyen-Orient', date: '1947-1949' },
  { war: 'Insurrection communiste malaise', location: 'Asie et Moyen-Orient', date: '1948-1960' },
  { war: 'Conflit armé birman', location: 'Asie et Moyen-Orient', date: '1948-?' },
  { war: 'Conflit israélo-arabe', location: 'Asie et Moyen-Orient', date: '' },
  { war: 'Guerre israélo-arabe de 1948', location: 'Asie et Moyen-Orient', date: '1948-1949' },
  { war: 'Crise du canal de Suez', location: 'Asie et Moyen-Orient', date: '1956' },
  { war: 'Guerre des Six Jours', location: 'Asie et Moyen-Orient', date: '1967' },
  { war: "Guerre d'usure", location: 'Asie et Moyen-Orient', date: '1967-1970' },
  { war: 'Guerre du Kippour', location: 'Asie et Moyen-Orient', date: '1973' },
  { war: 'Opération Litani', location: 'Asie et Moyen-Orient', date: '1978' },
  { war: 'Opération Paix en Galilée', location: 'Asie et Moyen-Orient', date: '1982' },
  {
    war: 'Opération Justice rendue ou Guerre des Sept Jours',
    location: 'Asie et Moyen-Orient',
    date: '1993',
  },
  { war: 'Opération Raisins de la colère', location: 'Asie et Moyen-Orient', date: '1996' },
  { war: 'Conflit israélo-palestinien', location: 'Asie et Moyen-Orient', date: '1948-?' },
  { war: 'Première Intifada', location: 'Asie et Moyen-Orient', date: '1987-1993' },
  {
    war: 'Intervention militaire chinoise au Tibet',
    location: 'Asie et Moyen-Orient',
    date: '1950-1951',
  },
  { war: 'Guerre de Corée', location: 'Asie et Moyen-Orient', date: '1950-1953' },
  { war: 'Guerre civile laotienne', location: 'Asie et Moyen-Orient', date: '1953-1975' },
  {
    war: 'Première crise du détroit de Taïwan',
    location: 'Asie et Moyen-Orient',
    date: '1954-1955',
  },
  { war: 'Deuxième crise du détroit de Taïwan', location: 'Asie et Moyen-Orient', date: '1958' },
  { war: 'Crise de 1958 au Liban', location: 'Asie et Moyen-Orient', date: '1958' },
  { war: 'Soulèvement tibétain de 1959', location: 'Asie et Moyen-Orient', date: '1959' },
  {
    war: "Guerre du Viêt Nam ou seconde guerre d'Indochine",
    location: 'Asie et Moyen-Orient',
    date: '1960-1975',
  },
  { war: 'Opération Vijay', location: 'Asie et Moyen-Orient', date: '1961' },
  { war: 'Conflit kurde en Irak', location: 'Asie et Moyen-Orient', date: '1961-1991' },
  { war: 'Guerre sino-indienne', location: 'Asie et Moyen-Orient', date: '1962' },
  { war: 'Konfrontasi', location: 'Asie et Moyen-Orient', date: '1963-1966' },
  { war: 'Guerre civile du Yémen du Nord', location: 'Asie et Moyen-Orient', date: '1962-1970' },
  { war: 'Conflit en Papouasie occidentale', location: 'Asie et Moyen-Orient', date: '1963-?' },
  { war: 'Deuxième guerre indo-pakistanaise', location: 'Asie et Moyen-Orient', date: '1965' },
  {
    war: 'Massacres de 1965-1966 en Indonésie',
    location: 'Asie et Moyen-Orient',
    date: '1965-1966',
  },
  { war: 'Guerre civile cambodgienne', location: 'Asie et Moyen-Orient', date: '1967-1975' },
  {
    war: 'Conflit maritime inter-coréen ou Guerre du Crabe',
    location: 'Asie et Moyen-Orient',
    date: '1967-?',
  },
  {
    war: 'Conflit frontalier sino-soviétique de 1969',
    location: 'Asie et Moyen-Orient',
    date: '1969',
  },
  { war: 'Insurrection moro aux Philippines', location: 'Asie et Moyen-Orient', date: '1969-?' },
  { war: 'Septembre noir', location: 'Asie et Moyen-Orient', date: '1970- 1971' },
  { war: 'Troisième guerre indo-pakistanaise', location: 'Asie et Moyen-Orient', date: '1971' },
  { war: 'Guerre du Liban', location: 'Asie et Moyen-Orient', date: '1975-1990' },
  { war: 'Guerre du Timor oriental', location: 'Asie et Moyen-Orient', date: '1975-1999' },
  { war: 'Conflit hmong', location: 'Asie et Moyen-Orient', date: '1975-?' },
  {
    war: 'Insurrection des Frères musulmans en Syrie',
    location: 'Asie et Moyen-Orient',
    date: '1976-1982',
  },
  {
    war: "Seconde guerre civile cambodgienne ou troisième guerre d'Indochine",
    location: 'Asie et Moyen-Orient',
    date: '1978-1999',
  },
  { war: 'Guerre sino-vietnamienne', location: 'Asie et Moyen-Orient', date: '1979' },
  { war: 'Révolution iranienne', location: 'Asie et Moyen-Orient', date: '1979' },
  { war: "Guerre d'Afghanistan", location: 'Asie et Moyen-Orient', date: '1979-1989' },
  {
    war: 'Guerre Iran-Irak ou première guerre du Golfe',
    location: 'Asie et Moyen-Orient',
    date: '1980-1988',
  },
  {
    war: 'Bataille des plates-formes pétrolières Sassan et Sirri',
    location: 'Asie et Moyen-Orient',
    date: '1988',
  },
  { war: 'Guerre civile du Sri Lanka', location: 'Asie et Moyen-Orient', date: '1983- 2009' },
  { war: 'Conflit kurde en Turquie', location: 'Asie et Moyen-Orient', date: '1984-?' },
  { war: "Guerre d'Afghanistan", location: 'Asie et Moyen-Orient', date: '1989-1992' },
  { war: 'Insurrection au Jammu-et-Cachemire', location: 'Asie et Moyen-Orient', date: '1989-?' },
  {
    war: 'Guerre du Golfe ou deuxième guerre du Golfe',
    location: 'Asie et Moyen-Orient',
    date: '1990-1991',
  },
  { war: 'Insurrection irakienne', location: 'Asie et Moyen-Orient', date: '1991' },
  { war: "Guerre d'Afghanistan", location: 'Asie et Moyen-Orient', date: '1992-1996' },
  { war: 'Guerre civile du Tadjikistan', location: 'Asie et Moyen-Orient', date: '1992-1997' },
  { war: 'Guerre civile au Yémen de 1994', location: 'Asie et Moyen-Orient', date: '1994' },
  { war: "Guerre d'Afghanistan", location: 'Asie et Moyen-Orient', date: '1996-2001' },
  { war: 'Guerre civile népalaise', location: 'Asie et Moyen-Orient', date: '1996-2006' },
  { war: 'Guerre du Yémen', location: 'Asie et Moyen-Orient', date: '1997-?' },
  { war: 'Insurrection djihadiste au Yémen', location: 'Asie et Moyen-Orient', date: '1997-?' },
  { war: 'Opération Infinite Reach', location: 'Asie et Moyen-Orient', date: '1998' },
  { war: 'Opération Desert Fox', location: 'Asie et Moyen-Orient', date: '1998' },
  { war: 'Conflit de Kargil', location: 'Asie et Moyen-Orient', date: '1999' },
  { war: 'Guerre civile grecque', location: 'Europe', date: '1946-1949' },
  { war: 'Violences inter-ethniques à Chypre', location: 'Europe', date: '1955-1967' },
  { war: "Guerre d'indépendance de Chypre", location: 'Europe', date: '1955-1959' },
  { war: 'Révolution hongroise de 1956', location: 'Europe', date: '1956' },
  { war: 'Conflit basque', location: 'Europe', date: '1959-2011' },
  {
    war: 'Invasion de la Tchécoslovaquie par le Pacte de Varsovie',
    location: 'Europe',
    date: '1968',
  },
  { war: 'Conflit nord-irlandais', location: 'Europe', date: '1969-1998' },
  { war: 'Invasion turque de Chypre', location: 'Europe', date: '1974' },
  { war: 'Guerre du Haut-Karabagh', location: 'Europe', date: '1988-1994' },
  { war: 'Révolution roumaine de 1989', location: 'Europe', date: '1989' },
  { war: 'Événements de janvier (Pays Baltes)', location: 'Europe', date: '1991' },
  { war: 'Conflit géorgien-ossète', location: 'Europe', date: '1989-?' },
  { war: 'Conflit abkhaze-géorgien', location: 'Europe', date: '1989-?' },
  { war: 'Guerre civile géorgienne', location: 'Europe', date: '1991-1993' },
  { war: "Première guerre d'Ossétie du Sud", location: 'Europe', date: '1991-1992' },
  { war: "Guerre d'Abkhazie", location: 'Europe', date: '1992-1993' },
  { war: 'Guerres de Yougoslavie', location: 'Europe', date: '1991-1999' },
  { war: 'Guerre de Slovénie', location: 'Europe', date: '1991' },
  { war: 'Guerre de Croatie', location: 'Europe', date: '1991-1995' },
  { war: 'Guerre de Bosnie-Herzégovine', location: 'Europe', date: '1992-1995' },
  { war: 'Guerre du Kosovo', location: 'Europe', date: '1998-1999' },
  { war: 'Guerre du Dniestr (Moldavie)', location: 'Europe', date: '1992' },
  { war: 'Conflit en Ossétie du Nord de 1992', location: 'Europe', date: '1992' },
  { war: 'Crise constitutionnelle russe', location: 'Europe', date: '1993' },
  { war: 'Première guerre de Tchétchénie', location: 'Europe', date: '1994-1996' },
  { war: 'Crise albanaise de 1997', location: 'Europe', date: '1997' },
  { war: "Guerre d'Abkhazie", location: 'Europe', date: '1998' },
  { war: 'Deuxième guerre de Tchétchénie', location: 'Europe', date: '1999-2009' },
  { war: 'Première Guerre mondiale', location: 'Monde', date: '1914-1918' },
  { war: 'Seconde Guerre mondiale', location: 'Monde', date: '1939-1945' },
  { war: 'Guerre froide', location: 'Monde', date: '1947-1991' },
  { war: "Crise politico-militaire en Côte d'Ivoire", location: 'Afrique', date: '2002-2007' },
  { war: 'Guerre du Darfour', location: 'Afrique', date: '2003-2020' },
  { war: 'Guerre du Sahel', location: 'Afrique', date: '2003-?' },
  { war: 'Guerre du Kivu', location: 'Afrique', date: '2004-?' },
  { war: 'Première guerre civile centrafricaine', location: 'Afrique', date: '2004-2007' },
  { war: 'Guerre civile tchadienne', location: 'Afrique', date: '2005-2010' },
  { war: 'Guerre civile somalienne', location: 'Afrique', date: '1991-?' },
  { war: 'Guerre civile somalienne', location: 'Afrique', date: '2006-?' },
  {
    war: "Lutte contre la Piraterie autour de la Corne de l'Afrique",
    location: 'Afrique',
    date: '',
  },
  { war: 'Combat au large de la Somalie le 18 mars 2006', location: 'Afrique', date: '2006' },
  {
    war: "Opération Atalante sous l'égide de l'Union Européenne",
    location: 'Afrique',
    date: '2008-?',
  },
  { war: "Opération Ocean Shield sous l'égide de l'OTAN", location: 'Afrique', date: '2009-2016' },
  { war: 'Intervention militaire du Kenya en Somalie', location: 'Afrique', date: '2011-?' },
  { war: 'Rébellions touarègues', location: 'Afrique', date: '' },
  { war: 'Rébellion touarègue au Mali (mai 2006-juillet 2006)', location: 'Afrique', date: '2006' },
  { war: 'Rébellion touarègue au Niger et au Mali', location: 'Afrique', date: '2007-2009' },
  {
    war: 'Rébellion touarègue au Mali (janvier 2012-avril 2012)',
    location: 'Afrique',
    date: '2012',
  },
  { war: 'Violences postélectorales au Kenya en 2007-2008', location: 'Afrique', date: '' },
  { war: 'Opération Démocratie aux Comores', location: 'Afrique', date: '2008' },
  { war: 'Guerre djibouto-érythréenne', location: 'Afrique', date: '2008' },
  { war: 'Insurrection de Boko Haram', location: 'Afrique', date: '2009-?' },
  { war: 'Crise ivoirienne de 2010-2011', location: 'Afrique', date: '2010-2011' },
  { war: 'Révolution tunisienne', location: 'Afrique', date: '2010-2011' },
  { war: 'Révolution égyptienne de 2011', location: 'Afrique', date: '2011' },
  { war: 'Insurrection du Sinaï', location: 'Afrique', date: '2011-?' },
  { war: 'Première guerre civile libyenne', location: 'Afrique', date: '2011' },
  {
    war: "Intervention militaire de 2011 en Libye sous l'égide de l'ONU",
    location: 'Afrique',
    date: '2011',
  },
  { war: 'Conflit au Kordofan du Sud', location: 'Afrique', date: '2011-2020' },
  { war: 'Guerre du Mali', location: 'Afrique', date: '2012- ?' },
  { war: 'Rébellion du M23 (Kivu)', location: 'Afrique', date: '2012-2013' },
  { war: 'Deuxième guerre civile centrafricaine', location: 'Afrique', date: '2012-2013' },
  { war: 'Troisième guerre civile centrafricaine', location: 'Afrique', date: '2013-2014' },
  { war: 'Opération Sangaris', location: 'Afrique', date: '2013-2016' },
  { war: 'Guerre civile sud-soudanaise', location: 'Afrique', date: '2013-2020' },
  { war: 'Insurrection du RENAMO (Mozambique)', location: 'Afrique', date: '2013- 2016' },
  { war: 'Deuxième guerre civile libyenne', location: 'Afrique', date: '2014- 2020' },
  { war: 'Crise burundaise', location: 'Afrique', date: '2015-2020' },
  { war: 'Guerre du Pool', location: 'Afrique', date: '2016-2017' },
  {
    war: 'Rébellion des Kamwina Nsapu (République démocratique du Congo)',
    location: 'Afrique',
    date: '2016-2019',
  },
  { war: 'Insurrection djihadiste au Mozambique', location: 'Afrique', date: '2017- ?' },
  { war: 'Crise anglophone au Cameroun', location: 'Afrique', date: '2017- ?' },
  { war: 'Guerre du Tigré', location: 'Afrique', date: '2020-2022' },
  { war: 'Conflit au Sahara occidental', location: 'Afrique', date: '2020- ?' },
  { war: 'Affrontements soudano-éthiopiens de 2020-2022', location: 'Afrique', date: '2020-2022' },
  { war: 'Offensive du Kanem (Tchad)', location: 'Afrique', date: '2021' },
  { war: 'Guerre civile soudanaise', location: 'Afrique', date: '2023- ?' },
  { war: "Coup d'état de 2004 en Haïti", location: 'Amérique centrale', date: '2004' },
  { war: 'Guerre de la drogue au Mexique', location: 'Amérique centrale', date: '2006-?' },
  { war: 'Crise haïtienne', location: 'Amérique centrale', date: '2017-?' },
  { war: 'Guerre des gangs en Haïti', location: 'Amérique centrale', date: '2020-?' },
  { war: 'Conflit israélo-palestinien', location: 'Asie et Moyen-Orient', date: '1948-?' },
  { war: 'Seconde Intifada', location: 'Asie et Moyen-Orient', date: '2000-2005' },
  { war: 'Guerre de Gaza de 2008-2009', location: 'Asie et Moyen-Orient', date: '2008-2009' },
  { war: 'Guerre de Gaza de 2012', location: 'Asie et Moyen-Orient', date: '2012' },
  { war: 'Guerre de Gaza de 2014', location: 'Asie et Moyen-Orient', date: '2014' },
  { war: 'Intifada des couteaux', location: 'Asie et Moyen-Orient', date: '2015-2017' },
  { war: 'Guerre israélo-palestinienne de 2021', location: 'Asie et Moyen-Orient', date: '2021' },
  { war: 'Crise israélo-palestinienne de 2023', location: 'Asie et Moyen-Orient', date: '2023' },
  { war: 'Guerre de Gaza', location: 'Asie et Moyen-Orient', date: '2023-?' },
  { war: 'Crise de la mer Rouge', location: 'Asie et Moyen-Orient', date: '2023-?' },
  { war: "Guerre d'Afghanistan", location: 'Asie et Moyen-Orient', date: '2001-2021' },
  { war: 'Conflit du Panchir', location: 'Asie et Moyen-Orient', date: '2021-?' },
  { war: 'Guerre du Yémen', location: 'Asie et Moyen-Orient', date: '1997-?' },
  { war: 'Insurrection houthiste au Yémen', location: 'Asie et Moyen-Orient', date: '2004-?' },
  { war: 'Guerre du Saada', location: 'Asie et Moyen-Orient', date: '2004-2014' },
  { war: 'Guerre civile yéménite', location: 'Asie et Moyen-Orient', date: '2014-?' },
  { war: 'Opération Tempête décisive', location: 'Asie et Moyen-Orient', date: '2015' },
  { war: "Opération Restaurer l'espoir", location: 'Asie et Moyen-Orient', date: '2015-?' },
  { war: 'Révolution yéménite', location: 'Asie et Moyen-Orient', date: '2011-2012' },
  { war: "Guerre d'Irak", location: 'Asie et Moyen-Orient', date: '2003-2011' },
  {
    war: "Invasion de l'Irak par les États-Unis en 2003",
    location: 'Asie et Moyen-Orient',
    date: '2003',
  },
  { war: 'Coalition militaire en Irak', location: 'Asie et Moyen-Orient', date: '2003-2011' },
  { war: 'Première guerre civile irakienne', location: 'Asie et Moyen-Orient', date: '2006-2008' },
  { war: 'Insurrection islamiste au Pakistan', location: 'Asie et Moyen-Orient', date: '2004-?' },
  {
    war: 'Attaques aériennes américaines au Pakistan',
    location: 'Asie et Moyen-Orient',
    date: '2004-?',
  },
  { war: 'Conflit dans le Sud de la Thaïlande', location: 'Asie et Moyen-Orient', date: '2004-?' },
  { war: 'Conflit israélo-libanais de 2006', location: 'Asie et Moyen-Orient', date: '' },
  {
    war: "Intervention de l'armée libanaise contre le mouvement islamiste armé Fatah al-Islam (Nahr el-Bared (Liban)).",
    location: 'Asie et Moyen-Orient',
    date: '2007',
  },
  { war: 'Conflit libanais de 2008', location: 'Asie et Moyen-Orient', date: '' },
  {
    war: 'Conflit frontalier entre la Thaïlande et le Cambodge autour du Temple de Preah Vihear',
    location: 'Asie et Moyen-Orient',
    date: '2008-2011',
  },
  { war: 'Soulèvement bahreïnien', location: 'Asie et Moyen-Orient', date: '2011' },
  { war: 'Guerre civile syrienne', location: 'Asie et Moyen-Orient', date: '2011-2024' },
  { war: 'Conflit au Liban', location: 'Asie et Moyen-Orient', date: '2011-2017' },
  {
    war: "Guerre contre l'État islamique en Irak et en Syrie",
    location: 'Asie et Moyen-Orient',
    date: '2014-2024',
  },
  {
    war: 'Intervention militaire de la Russie en Syrie',
    location: 'Asie et Moyen-Orient',
    date: '2015-2024',
  },
  { war: "Conflit dans l'État d'Arakan", location: 'Asie et Moyen-Orient', date: '2012' },
  { war: 'Seconde guerre civile irakienne', location: 'Asie et Moyen-Orient', date: '' },
  {
    war: "Guerre contre l'État islamique en Irak et en Syrie",
    location: 'Asie et Moyen-Orient',
    date: '2014-?',
  },
  { war: 'Conflit de Sabah', location: 'Asie et Moyen-Orient', date: '2013' },
  {
    war: "Tentative de coup d'État de 2016 en Turquie",
    location: 'Asie et Moyen-Orient',
    date: '2016',
  },
  { war: "Conflit dans l'État d'Arakan", location: 'Asie et Moyen-Orient', date: '2016-?' },
  {
    war: 'Confrontation indo-pakistanaise de 2019',
    location: 'Asie et Moyen-Orient',
    date: '2019',
  },
  { war: 'Combat de la vallée de Galwan', location: 'Asie et Moyen-Orient', date: '2020' },
  {
    war: 'Conflit de 2021 entre le Kirghizistan et le Tadjikistan',
    location: 'Asie et Moyen-Orient',
    date: '2021',
  },
  { war: 'Révolte de 2022 au Kazakhstan', location: 'Asie et Moyen-Orient', date: '2022' },
  { war: 'Guerre Israël-Hezbollah', location: 'Asie et Moyen-Orient', date: '2023-?' },
  { war: 'Crise indo-pakistanaise', location: 'Asie et Moyen-Orient', date: '2025-?' },
  { war: 'Conflit Iran-Israël de 2024-2025', location: 'Asie et Moyen-Orient', date: '2024-2025' },
  { war: 'Guerre Iran-Israël', location: 'Asie et Moyen-Orient', date: '2025' },
  {
    war: 'Crise frontalière de 2025 entre le Cambodge et la Thaïlande',
    location: 'Asie et Moyen-Orient',
    date: '2025-?',
  },
  {
    war: "Conflit de 2025 entre l'Afghanistan et le Pakistan",
    location: 'Asie et Moyen-Orient',
    date: '2025',
  },
  { war: 'Insurrection albanaise de 2001 en Macédoine', location: 'Europe', date: '2001' },
  { war: 'Crise de Kodori de 2001 (Géorgie)', location: 'Europe', date: '2001' },
  { war: 'Crise de la vallée de Pankissi (Géorgie)', location: 'Europe', date: '2002-2003' },
  { war: 'Guerre russo-géorgienne de 2008', location: 'Europe', date: '2008' },
  { war: 'Guérilla en Ciscaucasie', location: 'Europe', date: '2009- ?' },
  { war: 'Guerre russo-ukrainienne', location: 'Europe', date: '2014-?' },
  { war: 'Révolution de la dignité', location: 'Europe', date: '2014' },
  { war: 'Annexion de la Crimée par la Russie', location: 'Europe', date: '2014' },
  { war: 'Guerre du Donbass', location: 'Europe', date: '2014-2022' },
  { war: "Invasion de l'Ukraine par la Russie", location: 'Europe', date: '2022 - ?' },
  { war: 'Conflit frontalier au Haut-Karabagh', location: 'Europe', date: '1988-2024' },
  { war: 'Guerre des Quatre Jours', location: 'Europe', date: '2016' },
  { war: 'Guerre de 2020 au Haut-Karabagh', location: 'Europe', date: '2020' },
  {
    war: "Crise frontalière entre l'Arménie et l'Azerbaïdjan de 2021-2023",
    location: 'Europe',
    date: '2021-2023',
  },
  { war: 'Conflit arméno-azéribaïdjanais de septembre 2022', location: 'Europe', date: '2022' },
  { war: 'Guerre de 2023 au Haut-Karabagh', location: 'Europe', date: '2023' },
];
